package main

var answerWords = []string{
	"about", "above", "abuse", "acted", "acute", "admit", "adopt", "adult",
	"after", "again", "agent", "agree", "ahead", "aisle", "alarm", "album",
	"alert", "alike", "align", "alive", "allay", "alley", "allow", "alone",
	"along", "alter", "amber", "amble", "amend", "amiss", "ample", "amuse",
	"angel", "angle", "angry", "ankle", "annex", "apple", "apply", "arena",
	"argue", "arise", "armor", "arson", "aside", "atone", "attic", "audit",
	"avail", "avoid", "awake", "award", "aware", "awful", "azure", "abbey",
	"abode", "afoot", "agile", "aging", "aided", "ailed", "aired", "alder",
	"algae", "aloft", "altar", "angst", "annul", "anvil", "apron", "aptly",
	"badly", "baker", "baron", "basic", "beach", "beard", "beast", "began",
	"begin", "below", "berth", "birch", "birth", "black", "blade", "blame",
	"bland", "blank", "blaze", "bleak", "bleed", "bless", "blink", "bliss",
	"bloat", "block", "blood", "blown", "blues", "blunt", "blush", "bonus",
	"botch", "brace", "braid", "brand", "brave", "brawl", "bread", "break",
	"breed", "bribe", "bride", "brief", "brine", "brink", "brisk", "broad",
	"broke", "brook", "broom", "broth", "brown", "brush", "bumpy", "bunch",
	"burst", "buyer", "bandy", "barge", "batty", "beady", "blimp", "burly",
	"cable", "candy", "cargo", "catch", "cause", "cedar", "chain", "chalk",
	"charm", "chase", "cheap", "check", "chess", "child", "chill", "chunk",
	"civic", "civil", "claim", "clash", "clean", "clear", "clerk", "click",
	"cliff", "cling", "cloak", "clock", "clone", "close", "cloth", "cloud",
	"clown", "comet", "comic", "could", "count", "court", "cover", "craft",
	"crane", "crank", "creak", "cream", "creek", "creep", "crest", "crime",
	"crisp", "croak", "cross", "crowd", "crown", "crude", "cruel", "crush",
	"curve", "cadet", "canal", "carve", "chart", "chasm", "chimp", "chord",
	"chore", "chump", "cinch", "cleft", "clump", "clunk", "colon", "comfy",
	"crimp", "crust", "crypt", "camel", "carol",
	"dance", "datum", "death", "debut", "decay", "delta", "depth", "devil",
	"digit", "ditch", "dizzy", "donor", "doubt", "dough", "draft", "drain",
	"drama", "drape", "drawn", "dread", "dream", "dress", "drift", "drink",
	"drove", "drown", "dunce", "dwell", "dying", "daddy", "daisy", "dandy",
	"depot", "derby", "detox", "ditty", "dolly",
	"eager", "eagle", "early", "earth", "eight", "elite", "ember", "empty",
	"enact", "enemy", "enjoy", "enter", "envoy", "epoch", "equal", "error",
	"essay", "event", "every", "exact", "exert", "exist", "extra", "eclat",
	"eerie", "elbow", "elope", "emery", "emote", "evoke", "eyrie",
	"faint", "fairy", "faith", "false", "fancy", "feast", "fence", "fever",
	"field", "fight", "final", "fixed", "flame", "flare", "flask", "flesh",
	"flick", "fling", "flock", "flood", "floor", "flour", "flunk", "flute",
	"foggy", "force", "forge", "found", "frame", "fraud", "fresh", "front",
	"frost", "fruit", "femur", "ferry", "fetch", "flaky", "floss", "foray",
	"froze", "fully", "funky", "fussy",
	"gaudy", "ghost", "given", "glass", "glaze", "gleam", "glide", "glint",
	"gloom", "gloss", "glove", "going", "grace", "grade", "grain", "grand",
	"grant", "grape", "grasp", "grate", "grave", "greed", "greet", "grief",
	"grind", "groan", "gross", "group", "growl", "guess", "guest", "guide",
	"guild", "guile", "gusto", "gauze", "giddy", "gland", "glyph", "gnash",
	"gnome", "gorge",
	"habit", "happy", "harsh", "haven", "heard", "heart", "heavy", "hence",
	"herbs", "hinge", "hoard", "honey", "honor", "horse", "hotel", "house",
	"human", "humid", "humor", "hurry", "hyena", "hippo", "hoary", "husky",
	"ideal", "image", "imply", "infer", "inner", "input", "issue", "ivory",
	"icing", "irate", "irked", "irony",
	"jaded", "jazzy", "jelly", "jewel", "judge", "juice", "juicy", "jumpy",
	"jiffy", "joust", "junta",
	"kebab", "kitty", "knack", "knife", "knock", "knoll", "known", "kudos",
	"kinky",
	"labor", "lance", "large", "laser", "latch", "later", "layer", "leafy",
	"learn", "lease", "least", "leave", "ledge", "legal", "lemon", "level",
	"light", "limit", "liner", "liver", "logic", "loose", "lover", "lower",
	"lucky", "lunge", "lingo", "lusty",
	"magic", "major", "maker", "manor", "maple", "march", "marsh", "match",
	"mayor", "mercy", "merge", "metal", "might", "minor", "mixed", "model",
	"money", "month", "moral", "motif", "motor", "motto", "mound", "mouse",
	"mouth", "muddy", "mural", "music", "musty", "media", "mimic", "minus",
	"morph", "moult",
	"naive", "nasty", "naval", "nerve", "night", "noble", "noise", "nomad",
	"notch", "novel", "nudge", "nurse", "nymph",
	"occur", "ocean", "often", "opera", "optic", "orbit", "order", "other",
	"otter", "outer", "olive", "onset", "ovary", "ovoid", "oxide", "ozone",
	"paint", "pansy", "parse", "party", "pasta", "patch", "pause", "peace",
	"perch", "phase", "phone", "photo", "piece", "pilot", "place", "plain",
	"plane", "plank", "plant", "plead", "pleat", "pluck", "plumb", "plume",
	"plump", "poach", "point", "porch", "pound", "power", "prank", "press",
	"price", "pride", "prime", "print", "prism", "probe", "prune", "pudgy",
	"pulse", "punch", "purse", "papal", "pixel", "pizza", "plaza", "plunk",
	"prone", "psalm",
	"quack", "quail", "quake", "queen", "query", "quest", "quick", "quiet",
	"quill", "quirk", "quota", "quote", "quell",
	"rabbi", "radar", "raise", "rally", "ranch", "range", "rapid", "raven",
	"reach", "react", "realm", "recap", "refer", "reign", "relax", "repay",
	"repel", "reply", "rider", "ridge", "rifle", "right", "rigid", "risky",
	"rival", "river", "rivet", "roast", "rocky", "rough", "round", "rouse",
	"route", "royal", "ruler", "rusty", "ramen", "repro", "rerun", "resin",
	"retro", "retry", "reuse", "rouge",
	"saint", "savvy", "scary", "scene", "scent", "scoff", "scope", "score",
	"scour", "scout", "seize", "sense", "serve", "shaft", "shall", "shame",
	"shape", "share", "sharp", "shear", "sheer", "shelf", "shell", "shift",
	"shine", "shirt", "shore", "short", "shout", "shove", "shown", "shrub",
	"siege", "silly", "since", "skill", "skull", "slant", "slept", "slick",
	"slide", "slope", "sloth", "smash", "smell", "smile", "smoke", "snack",
	"snare", "sneak", "sniff", "solar", "solid", "solve", "sorry", "south",
	"space", "spare", "spark", "speak", "spear", "spend", "spine", "spite",
	"split", "spoke", "spoon", "sport", "spout", "stack", "staff", "stage",
	"stain", "stair", "stake", "stale", "stall", "stamp", "stand", "stare",
	"start", "state", "stead", "steel", "steep", "steer", "stern", "stiff",
	"still", "stock", "stomp", "stone", "store", "storm", "story", "stout",
	"strap", "straw", "stray", "strip", "stuck", "study", "stump", "style",
	"sugar", "surge", "swamp", "swear", "sweat", "sweep", "sweet", "swept",
	"swift", "sword", "sadly", "salve", "scram", "scrub", "sided", "sigma",
	"sized", "skimp", "slime", "sling", "slink", "slurp", "smear", "smelt",
	"smirk", "snaky", "snore", "snort", "spawn", "spill", "spook", "spree",
	"sprig", "spunk", "squad", "squat", "stunt", "suave", "suite", "swore",
	"table", "taken", "talon", "tango", "teach", "tease", "teeth", "tense",
	"tepid", "terse", "theme", "thick", "thorn", "those", "three", "thump",
	"tiger", "tight", "timer", "tipsy", "title", "today", "token", "tonic",
	"tooth", "torch", "total", "touch", "tough", "trace", "track", "trade",
	"trail", "train", "trait", "tramp", "tread", "trend", "trial", "tribe",
	"trick", "tried", "troop", "trout", "trove", "truce", "truly", "trunk",
	"trust", "truth", "tulip", "tumor", "typed", "tapir", "tawny", "tenth",
	"tonal", "trice", "truss", "trump", "tunic", "tuple", "tying",
	"ultra", "under", "until", "upset", "urban", "usher", "usual", "utter",
	"ulcer", "uncut", "unfit", "unity", "untie",
	"valid", "value", "vapor", "vault", "venom", "verse", "vigor", "viola",
	"viper", "viral", "vista", "vital", "vivid", "vocal", "voice", "voter",
	"vaunt", "vicar", "vixen", "voila",
	"wager", "waltz", "waste", "watch", "water", "weary", "weave", "wedge",
	"weird", "whale", "wheat", "wheel", "where", "white", "whole", "whose",
	"wield", "witch", "witty", "world", "worry", "worse", "worst", "wrath",
	"wring", "write", "wrong", "winch", "woken", "woven",
	"xenon", "yacht", "yearn", "yield", "young", "youth", "zebra", "zippy",
	"zingy", "zonal",
}
